spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviebooking?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
logging:
  level:
    root: INFO
server:
  port: 8080
  error:
    include-message: always
